# Generated by Django 6.0 on 2025-12-06 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('initial_capital', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('current_capital', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('total_trades', models.IntegerField(default=0)),
                ('consecutive_wins', models.IntegerField(default=0)),
                ('consecutive_losses', models.IntegerField(default=0)),
                ('max_consecutive_wins', models.IntegerField(default=0)),
                ('max_consecutive_losses', models.IntegerField(default=0)),
                ('max_capital', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('max_drawdown_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_performance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_number', models.IntegerField()),
                ('capital_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capital_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('risk_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outcome_multiplier', models.DecimalField(decimal_places=2, max_digits=6)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_win', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='home.tradingsession')),
            ],
            options={
                'ordering': ['trade_number'],
            },
        ),
    ]
