# Generated by Django 6.0 on 2025-12-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsession',
            name='outcomes_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
