# Generated by Django 6.0 on 2025-12-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_simulations', models.IntegerField()),
                ('completed_simulations', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=100)),
                ('strategy_key', models.CharField(max_length=50)),
                ('parameters', models.JSONField()),
                ('num_trades', models.IntegerField()),
                ('initial_capital', models.DecimalField(decimal_places=2, default=10000, max_digits=15)),
                ('final_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('final_performance_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_drawdown_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_performance_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_risk_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('avg_risk_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('avg_profit_loss', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_consecutive_wins', models.IntegerField()),
                ('max_consecutive_losses', models.IntegerField()),
                ('success_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_wins', models.IntegerField()),
                ('total_losses', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['strategy_key'], name='money_manag_strateg_fbc181_idx'), models.Index(fields=['batch_id'], name='money_manag_batch_i_4300c4_idx'), models.Index(fields=['final_performance_pct'], name='money_manag_final_p_bed401_idx'), models.Index(fields=['max_drawdown_pct'], name='money_manag_max_dra_0c7ec1_idx')],
            },
        ),
    ]
