# Generated by Django 6.0 on 2025-12-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationbatch',
            name='has_equity_curves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='equity_curve',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
