# Generated by Django 6.0 on 2025-12-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0002_simulationbatch_has_equity_curves_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_key', models.CharField(max_length=50, unique=True)),
                ('strategy_name', models.CharField(max_length=100)),
                ('reference_params', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['strategy_key'],
            },
        ),
    ]
